### ISSUE TITLE
Django transition

### ISSUE THREAD

**Issue by sirodoht** [OKThess/website#7]
Things left to do, to complete the transition of existing code base:
* [x] Favicon
* [x] Google Fonts
* [x] Google Analytics

Pages:
* [x] Homepage
* [x] About
* [x] Teams
* [x] News
* [x] Knowledge base
* [x] Apply
* [x] Contact

**Comment by ntemposd** [comment]
**Fresh!**

Teams page should also include Mentors, Hosted Meetups, Coworkings.
